---
kind: pipeline
type: docker
name: debian/amd64

platform:
  os: linux
  arch: amd64

steps:
- name: bullseye/tags
  image: alpine
  commands:
  - env | sort
  - docker/tags.sh | tee .tags
  environment:
    ARCH: amd64
    DATE: 20200607

- name: bullseye/dryrun
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:bullseye-20200607-slim
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: arescentral/deb-bullseye
    username:
      from_secret: docker_username
  when:
    ref:
      exclude:
      - refs/heads/master
      - refs/tags/*

- name: bullseye/image
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:bullseye-20200607-slim
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: arescentral/deb-bullseye
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

- name: buster/tags
  image: alpine
  commands:
  - env | sort
  - docker/tags.sh | tee .tags
  environment:
    ARCH: amd64
    DATE: 20200607

- name: buster/dryrun
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:buster-20200607-slim
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: arescentral/deb-buster
    username:
      from_secret: docker_username
  when:
    ref:
      exclude:
      - refs/heads/master
      - refs/tags/*

- name: buster/image
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:buster-20200607-slim
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: arescentral/deb-buster
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

- name: stretch/tags
  image: alpine
  commands:
  - env | sort
  - docker/tags.sh | tee .tags
  environment:
    ARCH: amd64
    DATE: 20200607

- name: stretch/dryrun
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:stretch-20200607-slim
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: arescentral/deb-stretch
    username:
      from_secret: docker_username
  when:
    ref:
      exclude:
      - refs/heads/master
      - refs/tags/*

- name: stretch/image
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:stretch-20200607-slim
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: arescentral/deb-stretch
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

---
kind: pipeline
type: docker
name: debian/arm64

platform:
  os: linux
  arch: arm64

steps:
- name: bullseye/tags
  image: alpine
  commands:
  - env | sort
  - docker/tags.sh | tee .tags
  environment:
    ARCH: arm64
    DATE: 20200607

- name: bullseye/dryrun
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:bullseye-20200607-slim
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: arescentral/deb-bullseye
    username:
      from_secret: docker_username
  when:
    ref:
      exclude:
      - refs/heads/master
      - refs/tags/*

- name: bullseye/image
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:bullseye-20200607-slim
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: arescentral/deb-bullseye
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

- name: buster/tags
  image: alpine
  commands:
  - env | sort
  - docker/tags.sh | tee .tags
  environment:
    ARCH: arm64
    DATE: 20200607

- name: buster/dryrun
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:buster-20200607-slim
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: arescentral/deb-buster
    username:
      from_secret: docker_username
  when:
    ref:
      exclude:
      - refs/heads/master
      - refs/tags/*

- name: buster/image
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:buster-20200607-slim
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: arescentral/deb-buster
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

- name: stretch/tags
  image: alpine
  commands:
  - env | sort
  - docker/tags.sh | tee .tags
  environment:
    ARCH: arm64
    DATE: 20200607

- name: stretch/dryrun
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:stretch-20200607-slim
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: arescentral/deb-stretch
    username:
      from_secret: docker_username
  when:
    ref:
      exclude:
      - refs/heads/master
      - refs/tags/*

- name: stretch/image
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:stretch-20200607-slim
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: arescentral/deb-stretch
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

---
kind: pipeline
type: docker
name: debian/arm

platform:
  os: linux
  arch: arm

steps:
- name: bullseye/tags
  image: alpine
  commands:
  - env | sort
  - docker/tags.sh | tee .tags
  environment:
    ARCH: arm
    DATE: 20200607

- name: bullseye/dryrun
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:bullseye-20200607-slim
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: arescentral/deb-bullseye
    username:
      from_secret: docker_username
  when:
    ref:
      exclude:
      - refs/heads/master
      - refs/tags/*

- name: bullseye/image
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:bullseye-20200607-slim
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: arescentral/deb-bullseye
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

- name: buster/tags
  image: alpine
  commands:
  - env | sort
  - docker/tags.sh | tee .tags
  environment:
    ARCH: arm
    DATE: 20200607

- name: buster/dryrun
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:buster-20200607-slim
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: arescentral/deb-buster
    username:
      from_secret: docker_username
  when:
    ref:
      exclude:
      - refs/heads/master
      - refs/tags/*

- name: buster/image
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:buster-20200607-slim
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: arescentral/deb-buster
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

- name: stretch/tags
  image: alpine
  commands:
  - env | sort
  - docker/tags.sh | tee .tags
  environment:
    ARCH: arm
    DATE: 20200607

- name: stretch/dryrun
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:stretch-20200607-slim
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: arescentral/deb-stretch
    username:
      from_secret: docker_username
  when:
    ref:
      exclude:
      - refs/heads/master
      - refs/tags/*

- name: stretch/image
  image: plugins/docker
  settings:
    build_args:
    - BASE=debian:stretch-20200607-slim
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: arescentral/deb-stretch
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

---
kind: pipeline
type: docker
name: ubuntu/amd64

platform:
  os: linux
  arch: amd64

steps:
- name: focal/tags
  image: alpine
  commands:
  - env | sort
  - docker/tags.sh | tee .tags
  environment:
    ARCH: amd64
    DATE: 20200606

- name: focal/dryrun
  image: plugins/docker
  settings:
    build_args:
    - BASE=ubuntu:focal-20200606
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: arescentral/deb-focal
    username:
      from_secret: docker_username
  when:
    ref:
      exclude:
      - refs/heads/master
      - refs/tags/*

- name: focal/image
  image: plugins/docker
  settings:
    build_args:
    - BASE=ubuntu:focal-20200606
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: arescentral/deb-focal
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

- name: bionic/tags
  image: alpine
  commands:
  - env | sort
  - docker/tags.sh | tee .tags
  environment:
    ARCH: amd64
    DATE: 20200526

- name: bionic/dryrun
  image: plugins/docker
  settings:
    build_args:
    - BASE=ubuntu:bionic-20200526
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: arescentral/deb-bionic
    username:
      from_secret: docker_username
  when:
    ref:
      exclude:
      - refs/heads/master
      - refs/tags/*

- name: bionic/image
  image: plugins/docker
  settings:
    build_args:
    - BASE=ubuntu:bionic-20200526
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: arescentral/deb-bionic
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

- name: xenial/tags
  image: alpine
  commands:
  - env | sort
  - docker/tags.sh | tee .tags
  environment:
    ARCH: amd64
    DATE: 20200514

- name: xenial/dryrun
  image: plugins/docker
  settings:
    build_args:
    - BASE=ubuntu:xenial-20200514
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: arescentral/deb-xenial
    username:
      from_secret: docker_username
  when:
    ref:
      exclude:
      - refs/heads/master
      - refs/tags/*

- name: xenial/image
  image: plugins/docker
  settings:
    build_args:
    - BASE=ubuntu:xenial-20200514
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: arescentral/deb-xenial
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

- name: trusty/tags
  image: alpine
  commands:
  - env | sort
  - docker/tags.sh | tee .tags
  environment:
    ARCH: amd64
    DATE: 20201217

- name: trusty/dryrun
  image: plugins/docker
  settings:
    build_args:
    - BASE=ubuntu:trusty-20201217
    dockerfile: docker/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: arescentral/deb-trusty
    username:
      from_secret: docker_username
  when:
    ref:
      exclude:
      - refs/heads/master
      - refs/tags/*

- name: trusty/image
  image: plugins/docker
  settings:
    build_args:
    - BASE=ubuntu:trusty-20201217
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: arescentral/deb-trusty
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/*

---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: bullseye/template
  image: alpine
  commands:
  - docker/manifest.sh | tee .manifest.tmpl
  environment:
    CODENAME: bullseye
    DATE: 20200607

- name: bullseye
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: .manifest.tmpl
    username:
      from_secret: docker_username

- name: buster/template
  image: alpine
  commands:
  - docker/manifest.sh | tee .manifest.tmpl
  environment:
    CODENAME: buster
    DATE: 20200607

- name: buster
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: .manifest.tmpl
    username:
      from_secret: docker_username

- name: stretch/template
  image: alpine
  commands:
  - docker/manifest.sh | tee .manifest.tmpl
  environment:
    CODENAME: stretch
    DATE: 20200607

- name: stretch
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: .manifest.tmpl
    username:
      from_secret: docker_username

- name: focal/template
  image: alpine
  commands:
  - docker/manifest.sh | tee .manifest.tmpl
  environment:
    CODENAME: focal
    DATE: 20200606

- name: focal
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: .manifest.tmpl
    username:
      from_secret: docker_username

- name: bionic/template
  image: alpine
  commands:
  - docker/manifest.sh | tee .manifest.tmpl
  environment:
    CODENAME: bionic
    DATE: 20200526

- name: bionic
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: .manifest.tmpl
    username:
      from_secret: docker_username

- name: xenial/template
  image: alpine
  commands:
  - docker/manifest.sh | tee .manifest.tmpl
  environment:
    CODENAME: xenial
    DATE: 20200514

- name: xenial
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: .manifest.tmpl
    username:
      from_secret: docker_username

- name: trusty/template
  image: alpine
  commands:
  - docker/manifest.sh | tee .manifest.tmpl
  environment:
    CODENAME: trusty
    DATE: 20201217

- name: trusty
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: .manifest.tmpl
    username:
      from_secret: docker_username

depends_on:
- debian/amd64
- debian/arm64
- debian/arm
- ubuntu/amd64

...
